@startuml

hide empty members

interface Tile {
  void render(Renderer renderer)
}

interface Map2d<T>

interface Renderer {
  void renderRectangle()
  void renderCircle()
}
class CanvasRenderer

interface RenderTask {
  void render()
}
class Map2dRenderTask<T>
class PathRenderTask

interface TileSelector<T> {
  Tile select(T parameter)
}

Tile <|-- RectangleTile
Tile <|-- SphereTile
Tile <|-- ImageTile

Renderer <|-left- CanvasRenderer
Renderer *-- RenderTask

Map2dRenderTask *-- Map2d
Map2dRenderTask *-- TileSelector

PathRenderTask *-- Tile

TileSelector -- Tile

RenderTask <|-- Map2dRenderTask
RenderTask <|-- PathRenderTask

@enduml